import React, { useState } from "react";
import { X, Search } from "lucide-react";

function FilterBrand() {
  const brands = [
    { name: "98 Degree North", count: 237 },
    { name: "7 alt by Pantaloons", count: 234 },
    { name: "7 Cavalry", count: 190 },
    { name: "3Colors", count: 131 },
    { name: "7TH LEGION", count: 85 },
    { name: "4 TRIPLE O FIVE O BY MUFTI", count: 59 },
    { name: "7OUNCE", count: 42 },
    { name: "3BROS", count: 34 },
    { name: "9FIGR", count: 22 },
    { name: "513", count: 21 },
    { name: "24 Street", count: 10 },
    { name: "18th HighStreet", count: 5 },
    { name: "15BUTTONS", count: 5 },
    { name: "8SECONDS", count: 2 },
    { name: "Allen Solly", count: 1367 },
    { name: "ADRO", count: 1281 },
    { name: "Adidas", count: 957 },
    { name: "Arrow Sport", count: 796 },
    { name: "Aeropostale", count: 674 },
    { name: "ASCIS", count: 622 },
    { name: "Ajile by Pantaloons", count: 599 },
    { name: "AMERICAN EAGLE FITTERS", count: 595 },
    { name: "AUSK", count: 569 },
    { name: "Alcis", count: 543 },
    { name: "Arrow", count: 542 },
    { name: "appulse", count: 538 },
    { name: "Andamen", count: 381 },
    { name: "AUXAMIS", count: 214 },
    { name: "AD by Arvind", count: 206 },
    { name: "AMSWAN", count: 178 },
    { name: "AUSTIVO", count: 171 },
    { name: "Adidas Originals", count: 165 },
    { name: "ARMISTO", count: 158 },
    { name: "Antony Morato", count: 155 },
    { name: "Adobe", count: 153 },
    { name: "AUTNA", count: 143 },
    { name: "Anikmart", count: 142 },
    { name: "Arrow New York", count: 136 },
    { name: "ARRAY", count: 126 },
    { name: "ATHLISIS", count: 123 },
    { name: "ARISE", count: 123 },
    { name: "ARBOUR", count: 121 },
    { name: "ALARM", count: 103 },
    { name: "Alan Jones", count: 98 },
    { name: "AXMANN", count: 96 },
    { name: "Austin Wood", count: 95 },
    { name: "ATICX", count: 94 },
    { name: "Ascend 47", count: 80 },
    { name: "Allen Solly Sport", count: 72 },
    { name: "ARIIX", count: 67 },
    { name: "Athflex", count: 65 },
    { name: "Albion by CM", count: 63 },
    { name: "ACTOHOLIC", count: 57 },
    { name: "Allen Cooper", count: 55 },
    { name: "ASTHETIC NATION", count: 53 },
    { name: "Asthetic Bodies", count: 48 },
    { name: "ALCOTT", count: 47 },
    { name: "AEDENBURG", count: 44 },
    { name: "Antiloop", count: 42 },
    { name: "ANTHEM", count: 40 },
    { name: "Art By Ritik", count: 36 },
    { name: "AgAtelier", count: 32 },
    { name: "ATLANS", count: 30 },
    { name: "AGIL ARMERO", count: 28 },
    { name: "Anax Aesthetics", count: 27 },
    { name: "ARDEUR", count: 26 },
    { name: "AAYAN BABY", count: 26 },
    { name: "ABLING", count: 24 },
    { name: "ARTICALE", count: 23 },
    { name: "AYCS", count: 22 },
    { name: "ALMOST SANE", count: 22 },
    { name: "Allen Solly Tribe", count: 21 },
    { name: "AVEJO", count: 19 },
    { name: "Adrunaline Fit", count: 18 },
    { name: "ADORATE", count: 18 },
    { name: "ATTIITUDE", count: 17 },
    { name: "ALAKH HUB", count: 17 },
    { name: "abnorml.", count: 17 },
    { name: "Aux India Company", count: 16 },
    { name: "Aristitch", count: 16 },
    { name: "ATTITUDE START OF FASHION", count: 15 },
    { name: "AUSTIEX", count: 14 },
    { name: "ANML", count: 14 },
    { name: "ARMENOR", count: 13 },
    { name: "ARISTOBRAT", count: 12 },
    { name: "Anta", count: 12 },
    { name: "ADWYN PETER", count: 12 },
    { name: "A & Y", count: 12 },
    { name: "AVVA", count: 11 },
    { name: "Aerio", count: 11 },
    { name: "all yours", count: 10 },
    { name: "AGUANTE", count: 10 },
    { name: "anzeer", count: 9 },
    { name: "AMIGOS", count: 9 },
    { name: "Arya Giri", count: 8 },
    { name: "ARTLESS", count: 8 },
    { name: "AMMARZO", count: 8 },
    { name: "ALTINYILDIZ CLASSICS AC Co.", count: 8 },
    { name: "abof", count: 8 },
    { name: "A AND K", count: 7 },
    { name: "AMUL COMFY", count: 6 },
    { name: "ATLANCE", count: 5 },
    { name: "Adyavastram", count: 4 },
    { name: "Apraa & Parma", count: 3 },
    { name: "Afalusz", count: 3 },
    { name: "AAITHAN", count: 3 },
    { name: "Aventura Outfitters", count: 2 },
    { name: "American Crew", count: 2 },
    { name: "ALLEYRICH", count: 2 },
    { name: "aLL", count: 2 },
    { name: "Arrow Blue Jean Co.", count: 1 },
    { name: "ALAWO", count: 1 },
    { name: "Being Human", count: 4030 },
    { name: "Blackberrys", count: 3083 },
    { name: "Basics", count: 2862 },
    { name: "Banana Club", count: 1670 },
    { name: "Bewakoof", count: 1612 },
    { name: "BYFORD by Pantaloons", count: 1529 },
    { name: "BRAWNY BATTLER", count: 1345 },
    { name: "BEYOU FASHION", count: 1187 },
    { name: "Blisstone", count: 1129 },
    { name: "BAESD", count: 1074 },
    { name: "Bushirt", count: 1025 },
    { name: "boohooMAN", count: 971 },
    { name: "BULLMER", count: 906 },
    { name: "Beverly Hills Polo Club", count: 869 },
    { name: "Be Crazy", count: 814 },
    { name: "BENNY BROOKS", count: 774 },
    { name: "Bene Kleed", count: 759 },
    { name: "Blu MNKY", count: 695 },
    { name: "bigbanana", count: 687 },
    { name: "Beyoung", count: 628 },
    { name: "berry blues", count: 609 },
    { name: "BE POSITIVE", count: 521 },
    { name: "British Club", count: 462 },
    { name: "Besick", count: 407 },
    { name: "BEAT LONDON by PEPE JEANS", count: 340 },
    { name: "BDSQUARE", count: 322 },
    { name: "Black Collection", count: 319 },
    { name: "Big Hello - The Plus Life", count: 316 },
    { name: "BS BLUE SQUAD", count: 313 },
    { name: "Bonkers Corner", count: 303 },
    { name: "BEN SHERMAN", count: 300 },
    { name: "BRATMA", count: 266 },
    { name: "Bruun & Stengade", count: 229 },
    { name: "BROWN BROTHERS", count: 228 },
    { name: "bollti", count: 218 },
    { name: "BLACK BUCK", count: 193 },
    { name: "Bewakoof Plus", count: 193 },
    { name: "Bewakoof Heavy Duty", count: 184 },
    { name: "BODYACTIVE", count: 176 },
    { name: "Bloopers Store", count: 172 },
    { name: "Big Hello - The Plus Life", count: 74 },
    { name: "BOLLYWOO.OOO", count: 67 },
    { name: "Breakbounce", count: 66 },
    { name: "BLUENCE", count: 62 },
    { name: "BOMBAE TEES", count: 55 },
    { name: "BubbleTwyst", count: 51 },
    { name: "BOLDFIT", count: 46 },
    { name: "Bucciato Private Limited", count: 42 },
    { name: "bigbanana Originals", count: 42 },
    { name: "Belliskey", count: 40 },
    { name: "Burnt Umber", count: 38 },
    { name: "BUNCH OF BAD", count: 38 },
    { name: "BLUWEEA", count: 35 },
    { name: "Burton", count: 33 },
    { name: "Blue Buddha", count: 32 },
    { name: "BlendCulture", count: 32 },
    { name: "BHF", count: 30 },
    { name: "Body Mechanics", count: 28 },
    { name: "Bruun & Stengade", count: 27 },
    { name: "Bombay High", count: 27 },
    { name: "Backbenchers", count: 27 },
    { name: "BRACLO", count: 26 },
    { name: "BEVDAAS", count: 24 },
    { name: "Bonjour", count: 21 },
    { name: "BeriBlu", count: 21 },
    { name: "BURGER BAE", count: 18 },
    { name: "Baller Athletik", count: 17 },
    { name: "Big Bunny", count: 15 },
    { name: "Braveo", count: 14 },
    { name: "BESIMPLE", count: 14 },
    { name: "Ben Martin", count: 14 },
    { name: "BAWSE", count: 14 },
    { name: "bearbrother", count: 13 },
    { name: "borse lele", count: 11 },
    { name: "Balaji Trading Com", count: 11 },
    { name: "BLACK BLINK", count: 10 },
    { name: "Be Savage", count: 10 },
    { name: "Bumchums", count: 9 },
    { name: "BLUE TYGA", count: 9 },
    { name: "Bareblow", count: 9 },
    { name: "Bamboology", count: 8 },
    { name: "BRUTE FORCE", count: 7 },
    { name: "BRAVE SOUL", count: 7 },
    { name: "Benvenuto Grazie", count: 7 },
    { name: "BOMBAY TROOPER", count: 6 },
    { name: "BWG", count: 5 },
    { name: "bummer", count: 5 },
    { name: "BROWN BROTHERS", count: 5 },
    { name: "Blacksmith", count: 5 },
    { name: "BIS CREATIONS", count: 5 },
    { name: "BE AWARA", count: 5 },
    { name: "British Club", count: 4 },
    { name: "Blue Saint", count: 4 },
    { name: "BANGS AND CRACKLES", count: 4 },
    { name: "Bofrike", count: 3 },
    { name: "BUNKODE", count: 2 },
    { name: "BRONOMICS", count: 2 },
    { name: "BOYCOTT", count: 2 },
    { name: "Blu MNKY", count: 2 },
    { name: "BEAST CRICKET", count: 2 },
    { name: "BUMCHIQ", count: 1 },
    { name: "BRIEF CHICKADE", count: 1 },
    { name: "Bell Paper", count: 1 },
    { name: "Banana Labs", count: 1 },
    { name: "COLOR CAPITAL", count: 3242 },
    { name: "Calvin Klein Jeans", count: 1934 },
    { name: "Campus Sutra", count: 1142 },
    { name: "Celio", count: 930 },
    { name: "CASUALBUD", count: 925 },
    { name: "Cantabil", count: 778 },
    { name: "CHKOKKO", count: 737 },
    { name: "Classic Polo", count: 595 },
    { name: "Crimsoune Club", count: 477 },
    { name: "ColorPlus", count: 472 },
    { name: "CHOZI", count: 391 },
    { name: "Club York", count: 369 },
    { name: "CULT", count: 362 },
    { name: "Crazymonk", count: 317 },
    { name: "Crocodile", count: 315 },
    { name: "Camey", count: 258 },
    { name: "CLAFOUTIS", count: 217 },
    { name: "Columbia", count: 187 },
    { name: "Calvin Klein", count: 178 },
    { name: "CELSIUS", count: 175 },
    { name: "CAMLA", count: 169 },
    { name: "Converse", count: 130 },
    { name: "COBB", count: 127 },
    { name: "CRYPTIC", count: 107 },
    { name: "catch", count: 104 },
    { name: "Colors and Blends", count: 99 },
    { name: "CODE by Lifestyle", count: 99 },
    { name: "Cool Plus", count: 98 },
    { name: "CAPTCHA", count: 80 },
    { name: "CHKOKKO Plus", count: 71 },
    { name: "Christy World", count: 67 },
    { name: "CODE OF HONOUR", count: 61 },
    { name: "Clothe Funn", count: 60 },
    { name: "CANOE", count: 58 },
    { name: "Cloak & Decker by Monte Carlo", count: 57 },
    { name: "COMICSENSE", count: 49 },
    { name: "CLOFLIX", count: 46 },
    { name: "Cloak & Decker", count: 45 },
    { name: "CLAPTON", count: 45 },
    { name: "COLOR HUNT", count: 43 },
    { name: "Crazybee Tshirt", count: 39 },
    { name: "Chombooka", count: 38 },
    { name: "CS LIFE", count: 33 },
    { name: "Chennis", count: 30 },
    { name: "Coitonic", count: 29 },
    { name: "CHRISTONE", count: 26 },
    { name: "COTTON AVENUE", count: 25 },
    { name: "culish", count: 23 },
    { name: "Cloroot", count: 23 },
    { name: "Colorchakra", count: 22 },
    { name: "CAVA", count: 22 },
    { name: "Canjuice", count: 20 },
    { name: "CAVALLO by Linen Club", count: 18 },
    { name: "Canary London", count: 17 },
    { name: "CL SPORT", count: 16 },
    { name: "Chromozome", count: 15 },
    { name: "CABIN COMFY", count: 15 },
    { name: "Calm Down", count: 14 },
    { name: "Crazy Mosquitoes", count: 13 },
    { name: "COMBRAIDED", count: 13 },
    { name: "Code 61", count: 13 },
    { name: "Cayman", count: 13 },
    { name: "callaway", count: 11 },
    { name: "Creatures of Habit", count: 10 },
    { name: "Colt", count: 10 },
    { name: "CTRL+P", count: 9 },
    { name: "COVE AND LANE", count: 7 },
    { name: "CHIMPAAANZEE", count: 7 },
    { name: "CHANDRASTYLE", count: 6 },
    { name: "Cation", count: 5 },
    { name: "Capdazz", count: 5 },
    { name: "Calvin Klein Underwear", count: 5 },
    { name: "Cotstyle", count: 4 },
    { name: "Cherokee", count: 3 },
    { name: "Casual Tees", count: 3 },
    { name: "Creed", count: 2 },
    { name: "COOFT", count: 2 },
    { name: "Conditions Apply", count: 2 },
    { name: "Calizar", count: 2 },
    { name: "Cute Pals", count: 1 },
    { name: "COTTON ON", count: 1 },
    { name: "CLUBWIN", count: 1 },
    { name: "Clawear", count: 1 },
    { name: "ChaseOverIN", count: 1 },
    { name: "CHARACTR CO IN", count: 1 },
    { name: "Cannabie", count: 1 },
    { name: "Callino London", count: 1 },
    { name: "Duke", count: 1119 },
    { name: "Dollar", count: 588 },
    { name: "DILLINGER", count: 582 },
    { name: "DeFacto", count: 403 },
    { name: "Difference of Opinion", count: 372 },
    { name: "Decathlon", count: 348 },
    { name: "dostitch", count: 347 },
    { name: "Dennis Lingo", count: 288 },
    { name: "DOOR74", count: 195 },
    { name: "Dzant", count: 186 },
    { name: "Ducati", count: 167 },
    { name: "DAMENSCH", count: 151 },
    { name: "DIDA", count: 118 },
    { name: "DOMIN8", count: 92 },
    { name: "Disney by Wear Your Mind", count: 84 },
    { name: "DIXCY SCOTT", count: 73 },
    { name: "DCYPHR", count: 57 },
    { name: "Divra Clothing", count: 44 },
    { name: "Deefab", count: 43 },
    { name: "deb", count: 42 },
    { name: "DYCA", count: 40 },
    { name: "DENNISON", count: 39 },
    { name: "Dockers", count: 38 },
    { name: "Dravix", count: 36 },
    { name: "Dream of Glory Inc", count: 35 },
    { name: "Dogman", count: 35 },
    { name: "Dogi Verg", count: 35 },
    { name: "DAFABFIT", count: 33 },
    { name: "DRAGON HILL", count: 29 },
    { name: "Dadu Dayal", count: 28 },
    { name: "DRYP EVOLUT", count: 23 },
    { name: "Desi OG", count: 23 },
    { name: "Double Two", count: 22 },
    { name: "DIAZ", count: 22 },
    { name: "Darestyles", count: 20 },
    { name: "Diving Deep", count: 14 },
    { name: "Desi Minimals", count: 14 },
    { name: "DDOUDDOU", count: 14 },
    { name: "DEEPMAYRA COLLECTION", count: 12 },
    { name: "Dollar Bigboss", count: 11 },
    { name: "Dash and Dot", count: 9 },
    { name: "DREAM ISLAND", count: 8 },
    { name: "Dexter by Kook N Keech", count: 8 },
    { name: "Doodlage", count: 6 },
    { name: "DC by Wear Your Mind", count: 5 },
    { name: "Danvoir Paris", count: 5 },
    { name: "DOKCHAN", count: 3 },
    { name: "DC by Kook N Keech", count: 3 },
    { name: "DS WORLD", count: 2 },
    { name: "djbravo 47", count: 2 },
    { name: "DEEZENO", count: 2 },
    { name: "DANZA-SON", count: 2 },
    { name: "DRVP", count: 1 },
    { name: "DIXCY SCOTT MAXIMUS", count: 1 },
    { name: "DEVEINS", count: 1 },
    { name: "EPPE", count: 289 },
    { name: "Elibolz", count: 235 },
    { name: "ether", count: 225 },
    { name: "Edyssa", count: 189 },
    { name: "Enciger", count: 158 },
    { name: "Eszett", count: 141 },
    { name: "EAZY", count: 124 },
    { name: "ETC", count: 100 },
    { name: "Espanshe", count: 84 },
    { name: "encore by INVICTUS", count: 83 },
    { name: "Estilocus", count: 73 },
    { name: "EKSDEE", count: 67 },
    { name: "ECOLINE Clothing", count: 67 },
    { name: "EcoLove", count: 66 },
    { name: "EXILION", count: 56 },
    { name: "Eyebogler", count: 42 },
    { name: "ENDEAVOUR WEAR", count: 17 },
    { name: "Enchanted Drapes", count: 16 },
    { name: "Everestwolf", count: 13 },
    { name: "EQL", count: 12 },
    { name: "Eleven Brothers", count: 12 },
    { name: "effy", count: 10 },
    { name: "Echolope", count: 10 },
    { name: "Entertainment Store", count: 9 },
    { name: "ELPIDA", count: 9 },
    { name: "ETRO", count: 8 },
    { name: "Eyolf", count: 6 },
    { name: "EVERDION", count: 6 },
    { name: "Eton", count: 6 },
    { name: "ekchala", count: 5 },
    { name: "EROBOLD", count: 4 },
    { name: "ELBATROSS", count: 4 },
    { name: "Extra Butter", count: 1 },
    { name: "Emerals", count: 1 },
    { name: "Emartos", count: 1 },
    { name: "ELABORADO", count: 1 },
    { name: "Ecko Unltd", count: 1 },
    { name: "Friskers", count: 3349 },
    { name: "FABSTIEVE", count: 3049 },
    { name: "Flying Machine", count: 1627 },
    { name: "Fashnobic", count: 856 },
    { name: "FTX", count: 759 },
    { name: "FBAR", count: 733 },
    { name: "Fame Forever by Lifestyle", count: 622 },
    { name: "French Connection", count: 557 },
    { name: "Free Authority", count: 486 },
    { name: "Force NXT", count: 444 },
    { name: "FCUK", count: 414 },
    { name: "FUAARK", count: 349 },
    { name: "FLYIND VOGUE OUTFIT", count: 294 },
    { name: "Fleximaa", count: 241 },
    { name: "FROSEN FOX", count: 205 },
    { name: "Fred Perry", count: 200 },
    { name: "FARROWX", count: 127 },
    { name: "FALTU.CO", count: 116 },
    { name: "FORCE IX", count: 113 },
    { name: "FFLIRTYGO", count: 101 },
    { name: "FILA", count: 94 },
    { name: "Fans Army", count: 92 },
    { name: "FEVERFEW", count: 90 },
    { name: "Forca", count: 87 },
    { name: "f Gallery", count: 87 },
    { name: "FIFTY TWO", count: 85 },
    { name: "FLOSBERRY", count: 73 },
    { name: "fanideaz", count: 68 },
    { name: "Fasha", count: 66 },
    { name: "Fort Collins", count: 58 },
    { name: "FUGAZEE", count: 56 },
    { name: "FREECULTR", count: 55 },
    { name: "Forca by Lifestyle", count: 50 },
    { name: "FABRIPPLE", count: 49 },
    { name: "FOREVER 21", count: 47 },
    { name: "FAOES", count: 34 },
    { name: "Fox", count: 32 },
    { name: "FITINC", count: 31 },
    { name: "Fit Monkey", count: 31 },
    { name: "FUNDOO", count: 29 },
    { name: "FARICON", count: 29 },
    { name: "fast fashion", count: 27 },
    { name: "FREAKINS", count: 26 },
    { name: "Force", count: 23 },
    { name: "Fitkin", count: 22 },
    { name: "FICKA", count: 21 },
    { name: "Fashion2wear", count: 20 },
    { name: "FirstKrush", count: 19 },
    { name: "Farah", count: 19 },
    { name: "FRENCHIE", count: 18 },
    { name: "Fabindia", count: 18 },
    { name: "FiftyEight", count: 15 },
    { name: "FARDA", count: 12 },
    { name: "Fmagnet Clothing", count: 11 },
    { name: "FanCode Shop", count: 11 },
    { name: "FIRST SLEEP", count: 9 },
    { name: "FILO HEVIS", count: 8 },
    { name: "Frieza", count: 7 },
    { name: "FREBANO", count: 7 },
    { name: "FLAMBOYANT", count: 7 },
    { name: "FEVER HUNT", count: 7 },
    { name: "FC Barcelona", count: 7 },
    { name: "FASO", count: 7 },
    { name: "FABdon", count: 7 },
    { name: "Freeform by High Star", count: 6 },
    { name: "Franco Leone", count: 6 },
    { name: "FIBONACCI", count: 6 },
    { name: "FADMARK", count: 5 },
    { name: "FUBAR", count: 4 },
    { name: "FLYNOFF", count: 4 },
    { name: "FITIN OUTFIT", count: 4 },
    { name: "Firangi Yarn", count: 4 },
    { name: "Foomer", count: 3 },
    { name: "Fruit of the loom", count: 2 },
    { name: "FRENCH KLEIDER", count: 2 },
    { name: "Fear No Man", count: 2 },
    { name: "FastColors", count: 2 },
    { name: "FABESCA", count: 2 },
    { name: "FREE SOCIETY", count: 1 },
    { name: "FINAXO FASHION", count: 1 },
    { name: "Fiesto Fashion", count: 1 },
    { name: "FERANOID", count: 1 },
    { name: "FashionX", count: 1 },
  { name: "Greylongg", count: 7013 },
  { name: "glitchez", count: 2179 },
  { name: "GANT", count: 674 },
  { name: "Greenfibre", count: 564 },
  { name: "GLOBAL NOMAD", count: 560 },
  { name: "GET GOLF", count: 466 },
  { name: "GRIFFEL", count: 464 },
  { name: "GRACE & JACK", count: 356 },
  { name: "GAP", count: 312 },
  { name: "GUESS", count: 311 },
  { name: "Genzy", count: 207 },
  { name: "GLITO", count: 185 },
  { name: "GIORDANO", count: 150 },
  { name: "GRITSTONES", count: 137 },
  { name: "GRITPRO", count: 131 },
  { name: "GO DEVIL", count: 113 },
  { name: "GODFREY", count: 107 },
  { name: "GLOWBERRY", count: 104 },
  { name: "GRIMELANGE", count: 82 },
  { name: "Globus", count: 69 },
  { name: "GRACIT", count: 58 },
  { name: "Global Republic", count: 54 },
  { name: "Ghumakkad", count: 35 },
  { name: "GRAGE", count: 34 },
  { name: "Grit and Flair", count: 33 },
  { name: "GREENLANDS", count: 33 },
  { name: "Gajraj", count: 33 },
  { name: "Gildan", count: 30 },
  { name: "GESPO", count: 28 },
  { name: "GEE 5", count: 24 },
  { name: "GREATMAN", count: 23 },
  { name: "Getsetwear", count: 23 },
  { name: "GIG STORE", count: 20 },
  { name: "GAZELLE ACTIVE", count: 20 },
  { name: "Gfore", count: 18 },
  { name: "Grey&Bold", count: 17 },
  { name: "Golden Kite", count: 14 },
  { name: "GOKYO", count: 14 },
  { name: "GABBLE & WOLSH", count: 14 },
  { name: "Genius18", count: 9 },
  { name: "GYMYAK", count: 7 },
  { name: "GREEN AGE", count: 7 },
  { name: "GREENFLAIR", count: 6 },
  { name: "Garment Globe", count: 6 },
  { name: "Greeks and Truks", count: 4 },
  { name: "GUTI", count: 2 },
  { name: "Gizmoz", count: 1 },
  { name: "Givo", count: 1 },
    { name: "Gap", count: 2765 },
  { name: "HRX by Hrithik Roshan", count: 4907 },
  { name: "HIGHLANDER", count: 2408 },
  { name: "HERE&NOW", count: 2151 },
  { name: "Huetrap", count: 1534 },
  { name: "H&M", count: 690 },
  { name: "HESHA", count: 292 },
  { name: "Hypernation", count: 219 },
  { name: "Harvard", count: 210 },
  { name: "HACKETT LONDON", count: 178 },
  { name: "HOUSE OF VEDAS", count: 155 },
  { name: "HARBOR N BAY", count: 125 },
  { name: "HUSHBUCKS", count: 113 },
  { name: "Hubberholme", count: 93 },
  { name: "HAPPY KHAJANA", count: 77 },
  { name: "hummel", count: 70 },
  { name: "HOUSE OF RS", count: 67 },
  { name: "HOP HEAD", count: 65 },
  { name: "High Star", count: 64 },
  { name: "HEAST", count: 59 },
  { name: "Hardsoda by The Indian Garage Co", count: 57 },
  { name: "Hektor", count: 55 },
  { name: "HUEMN", count: 53 },
  { name: "Hikabae", count: 50 },
  { name: "HiFlyers", count: 43 },
  { name: "Hancock", count: 42 },
  { name: "House of Koala", count: 36 },
  { name: "HAUTEMODA", count: 32 },
  { name: "Hallstatt Life", count: 29 },
  { name: "Hatke Trends", count: 26 },
  { name: "Harfun", count: 26 },
  { name: "HangerLoop", count: 24 },
  { name: "Hidden Loops", count: 19 },
  { name: "HUGO", count: 18 },
  { name: "HJ HASASI", count: 17 },
  { name: "HAMPTONS", count: 17 },
  { name: "HILLBERG", count: 12 },
  { name: "HIRRUX", count: 11 },
  { name: "HOOD CULTURE", count: 10 },
  { name: "Hash and Dash", count: 10 },
  { name: "Haxor", count: 9 },
  { name: "HOUSE OF S", count: 7 },
  { name: "Hencemade", count: 7 },
  { name: "Hauntrex", count: 7 },
  { name: "Hallinton", count: 7 },
  { name: "HOODLER", count: 3 },
  { name: "Harashree", count: 3 },
  { name: "HOMEGROWN", count: 2 },
  { name: "HARSAM", count: 2 },
  { name: "HSNT", count: 1 },
  { name: "HOUSE OF MAITHILI", count: 1 },
  { name: "Hence", count: 1 },
  { name: "Indian Terrain", count: 687 },
  { name: "Instafab Plus", count: 318 },
  { name: "INVICTUS", count: 308 },
  { name: "Imsa Moda", count: 208 },
  { name: "Invincible", count: 162 },
  { name: "Iconic", count: 136 },
  { name: "INDISSH", count: 108 },
  { name: "IZOD", count: 63 },
  { name: "IVOC", count: 61 },
  { name: "INKMAN", count: 57 },
  { name: "INDIAN THREADS", count: 53 },
  { name: "INSPRIE", count: 49 },
  { name: "IMPACKT", count: 39 },
  { name: "inner element", count: 38 },
  { name: "INTERWOVE", count: 29 },
  { name: "I Am Animal", count: 18 },
  { name: "INDICLUB", count: 15 },
  { name: "IZF", count: 12 },
  { name: "IMYOUNG", count: 11 },
  { name: "IMPERATIVE", count: 10 },
  { name: "IDENTITI", count: 8 },
  { name: "Integriti", count: 7 },
  { name: "IMUCI", count: 5 },
  { name: "IX IMPRESSION", count: 4 },
  { name: "IMPERIO", count: 4 },
  { name: "Invictus Indoor", count: 2 },
  { name: "IMPORE", count: 2 },
  { name: "indian krait", count: 1 },
  { name: "IBERRY'S", count: 1 },
  {name:"Jack & Jones", count:1534},
  {name:"JADE BLUE", count:640},
  {name:"Jockey", count:543},
  {name:"Jack Paris", count:338},
  {name:"Jolie robe", count:254},
  {name:"Joven", count:202},
  {name:"John Pride", count:180},
  {name:"JUMP USA", count:162},
  {name:"JUMPCUTS", count:113},
  {name:"John Peters", count:95},
  {name:"JUARI BE A GENTLEMAN", count:57},
  {name:"Just Cavalli", count:54},
  {name:"JUNEBABY", count:51},
  {name:"Jinfo", count:41},
  {name:"JACKDANZA", count:35},
  {name:"JOLGER", count:33},
  {name:"Juxar", count:32},
  {name:"jugular", count:26},
  {name:"JACK NICKLAUS", count:26},
  {name:"JAVINISHKA", count:22},
  {name:"JOHN ELLIES", count:14},
  {name:"JINXER", count:9},
  {name:"JRCY", count:8},
  {name:"Jibumi", count:8},
  {name:"Justice League", count:5},
  {name:"JUNK de LUXE", count:5},
  {name:"John Players", count:5},
  {name:"Juventus F.C.", count:2},
  {name:"Jn Joy", count:2},
  {name:"JIMMY & JORDAN", count:1},
  {name:"JFR", count:1},

  {name:"KPOP", count:2448},
  {name:"Kook N Keech", count:2164},
  {name:"KAIDO", count:1104},
  {name:"Koton", count:705},
  {name:"Kalt", count:693},
  {name:"KaamBhari", count:354},
  {name:"KETCH", count:254},
  {name:"Kook N Keech Disney", count:218},
  {name:"Kushi Flyer", count:211},
  {name:"Kroptee", count:211},
  {name:"Kasendra", count:206},
  {name:"Kook N Keech Marvel", count:189},
  {name:"Kryptic", count:175},
  {name:"Kappa", count:137},
  {name:"Klub Fox", count:136},
  {name:"KOR", count:129},
  {name:"KAJARU", count:114},
  {name:"KASMA", count:92},
  {name:"KIABI", count:89},
  {name:"Karl Lagerfeld", count:76},
  {name:"KZ07 By Kazo", count:49},
  {name:"KOFFY", count:48},
  {name:"KAEZRI", count:43},
  {name:"Kotty", count:41},
  {name:"KAY DEE", count:40},
  {name:"Kook N Keech Batman", count:34},
  {name:"KINGDOM OF WHITE", count:33},
  {name:"KUNDAN", count:30},
  {name:"Kook N Keech Star Wars", count:27},
  {name:"KATSO", count:26},
  {name:"Kook N Keech Superman", count:24},
  {name:"KULTPRIT", count:23},
  {name:"KANWILLS", count:23},
  {name:"KRIMMPLE LOVE", count:20},
  {name:"KNN Calcutta", count:20},
  {name:"KEITH KARTER", count:20},
  {name:"Kolor Fusion", count:18},
  {name:"Kenneth Cole", count:18},
  {name:"Kook N Keech Looney Tunes", count:16},
  {name:"Kook N Keech Harry Potter", count:15},
  {name:"Kook N Keech Toons", count:12},
  {name:"KISSOSS", count:10},
  {name:"Kevior", count:10},
  {name:"Keepfit", count:10},
  {name:"KEX", count:9},
  {name:"KART BLACK", count:9},
  {name:"Kalt Plus", count:7},
  {name:"Kookaburra", count:6},
  {name:"Kveto style redefined", count:5},
  {name:"KOLORTHERAPI", count:5},
  {name:"KVETOO", count:4},
  {name:"KNYA", count:4},
  {name:"KOBO", count:3},
  {name:"Klart", count:3},
  {name:"Keenuu", count:3},
  {name:"KROSSSTITCH", count:1},
  {name:"Kraptick", count:1},
  {name:"Kook N Keech Emoji", count:1},
  {name:"KIDAROO", count:1},
  {name:"A MILANO", count:1174},
  {name:"Leotude", count:892},
  {name:"Levis", count:828},
  {name:"Louis Philippe", count:595},
  {name:"Lee", count:565},
  {name:"LUX NITRO", count:540},
  {name:"Louis Philippe Sport", count:526},
  {name:"LEON", count:448},
  {name:"Lux Cozi", count:428},
  {name:"Louis Philippe Jeans", count:420},
  {name:"Lacoste", count:322},
  {name:"LOUIS STITCH", count:233},
  {name:"LC Waikiki", count:210},
  {name:"LIMEROAD", count:186},
  {name:"LOCOMOTIVE", count:178},
  {name:"LINDBERGH", count:176},
  {name:"LE BOURGEOIS", count:98},
  {name:"LUX PARKER", count:96},
  {name:"LAUREN ADAMS", count:88},
  {name:"LYCOS", count:74},
  {name:"Lazy Lush", count:72},
  {name:"Loopers", count:48},
  {name:"Louis Bayrad", count:47},
  {name:"London Hills", count:45},
  {name:"Linen Club", count:43},
  {name:"Louis Philippe Ath.Work", count:34},
  {name:"Letshandcraft", count:33},
  {name:"LOVE PANGOLIN", count:31},
  {name:"LUMICCHI", count:29},
  {name:"Louis Philippe ATHPLAY", count:25},
  {name:"LUXURIT", count:22},
  {name:"LEE BONEE", count:20},
  {name:"Ludic", count:14},
  {name:"LOVEGEN", count:8},
  {name:"Lawman pg3", count:8},
  {name:"Lovable Sport", count:6},
  {name:"Looks United", count:6},
  {name:"Lyril", count:5},
  {name:"Luxure by Louis Philippe", count:3},
  {name:"Looney Tunes by Wear Your Mind", count:2},
  {name:"LELA", count:2},
  {name:"LBEE", count:2},
  {name:"LOVE RABBY", count:1},
  {name:"LAGAV", count:1},

  {name:"Moda Rapido", count:2445},
  {name:"Mast & Harbour", count:2095},
  {name:"MACK JONNEY", count:1471},
  {name:"Monte Carlo", count:1220},
  {name:"max", count:1024},
  {name:"MaverIQ", count:802},
  {name:"Maniac", count:686},
  {name:"MANGO MAN", count:680},
  {name:"Mufti", count:622},
  {name:"Masculino Latino", count:547},
  {name:"MISCHIEF MONKEY", count:400},
  {name:"Metronaut", count:345},
  {name:"Mad Over Print", count:339},
  {name:"MADSTO", count:303},
  {name:"Masculino Latino Plus", count:243},
  {name:"METTLE", count:232},
  {name:"Marvel by Wear Your Mind", count:226},
  {name:"Marks & Spencer", count:181},
  {name:"MERRIMENT", count:179},
  {name:"MOUNTAIN COLOURS", count:158},
  {name:"MARVEL STREET", count:158},
  {name:"MuscleBlaze", count:120},
  {name:"Mr Bowerbird", count:97},
  {name:"Markle Moro", count:87},
  {name:"MAXZONE", count:86},
  {name:"MASCLN SASSAFRAS", count:85},
  {name:"Muvazo", count:84},
  {name:"MUWIN", count:81},
  {name:"MEGHZ", count:58},
  {name:"MEGAKART", count:57},
  {name:"MOZIGO", count:56},
  {name:"METRONAUT PLUS", count:55},
  {name:"MONTCLAIR", count:53},
  {name:"MASTI TEES", count:52},
  {name:"MORDEN MUSE", count:47},
  {name:"Macaso Italy", count:46},
  {name:"MORSE CODE", count:44},
  {name:"Miaz Lifestyle", count:35},
  {name:"Matinique", count:34},
  {name:"MAATIR DESIGNS", count:32},
  {name:"MOUNTMILLER", count:29},
  {name:"MERCHANT MARINE", count:29},
  {name:"Melvin Jones", count:23},
  {name:"Musclemind", count:22},
  {name:"Midnight LAW", count:20},
  {name:"Minions by Kook N Keech", count:19},
  {name:"MENTOOS", count:19},
  {name:"MANTICORE", count:19},
  {name:"ministry", count:16},
  {name:"MONKSTORY", count:14},
  {name:"Mark Leute", count:14},
  {name:"MYEONN", count:13},
  {name:"Mountain Hardwear", count:13},
  {name:"Mumbai Indians", count:12},
  {name:"Minus One", count:11},
  {name:"MARK & ALBERT", count:11},
  {name:"Macy's Club Room", count:11},
  {name:"MOD ECRU", count:10},
  {name:"MIRAAN", count:10},
  {name:"MARCA Bold", count:10},
  {name:"MH&Y", count:9},
  {name:"Mesa", count:9},
  {name:"MotoGP", count:8},
  {name:"MONTREZ", count:8},
  {name:"Muffynn", count:7},
  {name:"MIMID", count:6},
  {name:"Macroman M-Series", count:6},
  {name:"M7 by Metronaut", count:6},
  {name:"Moonaa Fashion", count:5},
  {name:"M&H Our Water", count:5},
  {name:"M&H Easy", count:5},
  {name:"MOSCHINO COUTURE", count:4},
  {name:"MOHICANS", count:4},
  {name:"MODERN CREW", count:4},
  {name:"Mantonix", count:4},
  {name:"MTV", count:3},
  {name:"Masch Sports", count:3},
  {name:"Manchester City FC", count:3},
  {name:"mr lootera", count:2},
  {name:"Menkovy", count:2},
  {name:"ManQ CASUAL", count:2},
  {name:"Myrung", count:1},
  {name:"MR BUTTON", count:1},
  {name:"MensXP Basics", count:1},
  {name:"Mellow Clothing", count:1},
  {name:"MAZMUN", count:1},
  {name:"Marvel Avengers", count:1},
  {name:"MANRANGI", count:1},
  {name:"MAGNETO", count:1},

  {name:"NOBLE HUSTLE", count:1342},
  {name:"Nautica", count:1048},
  {name:"NOBERO", count:597},
  {name:"Nike", count:518},
  {name:"New Balance", count:301},
  {name:"Numero Uno", count:167},
  {name:"Naturebliss", count:159},
  {name:"NBA", count:158},
  {name:"NEXT", count:146},
  {name:"NEVA", count:73},
  {name:"Nins Moda", count:67},
  {name:"nostrum", count:66},
  {name:"N AND J", count:59},
  {name:"NYKER", count:51},
  {name:"NIVIA", count:48},
  {name:"NEON CHILLIE", count:33},
  {name:"NUSYL", count:30},
  {name:"New Theory", count:24},
  {name:"NEXSTYLO", count:19},
  {name:"NEVER LOSE", count:13},
  {name:"NAMASTRAY", count:12},
  {name:"No Nazar", count:11},
  {name:"NOTWILD", count:6},
  {name:"NoBiY", count:2},
  {name:"Nautankishaala", count:2},
  {name:"Nektar", count:1},

  {name:"Octave", count:1225},
  {name:"Organic Chics", count:780},
  {name:"ONN", count:359},
  {name:"OGEN", count:252},
  {name:"ONE SKY", count:213},
  {name:"OUTLAWS", count:171},
  {name:"OFF LIMITS", count:79},
  {name:"Overlays", count:78},
  {name:"Obaan", count:77},
  {name:"OWL MINK", count:74},
  {name:"ONEWAY", count:69},
  {name:"ODCC", count:61},
  {name:"Onfleeks", count:52},
  {name:"OBOW", count:50},
  {name:"OUTERWORLD", count:43},
  {name:"Oakmans", count:33},
  {name:"OXPECKER", count:30},
  {name:"OG For Real", count:28},
  {name:"Omtex", count:23},
  {name:"OTTO", count:22},
  {name:"Original Penguin", count:20},
  {name:"OTFIT", count:19},
  {name:"Offbeat Outfits", count:17},
  {name:"one8 x PUMA", count:15},
  {name:"ODETTE", count:12},
  {name:"OXYZONE", count:11},
  {name:"OUTDRIP", count:10},
  {name:"ONEMILE", count:4},
  {name:"OWR", count:3},
  {name:"ONLY & SONS", count:3},
  {name:"OI ODIN INDIA", count:3},
  {name:"Ostilos", count:2},
  {name:"Okane", count:2},
  {name:"ODDGRAB", count:2},
  {name:"ORIGIN BY ZALORA", count:1},
  {name:"OG THE ORIGINALS", count:1},

  {name:"Puma", count:1847},
  {name:"Pepe Jeans", count:1317},
  {name:"Peter England Casuals", count:579},
  {name:"Peter England", count:540},
  {name:"People", count:501},
  {name:"Park Avenue", count:455},
  {name:"Powerlook", count:411},
  {name:"PRONK", count:385},
  {name:"Parx", count:311},
  {name:"PUMA Motorsport", count:297},
  {name:"Peregrine by Pantaloons", count:280},
  {name:"PUNK", count:279},
  {name:"Polo Ralph Lauren", count:255},
  {name:"PULP", count:206},
  {name:"Petrol", count:177},
  {name:"Polo Plus", count:170},
  {name:"PAUL STREET", count:135},
  {name:"playR", count:131},
  {name:"Provogue", count:126},
  {name:"PockMAN", count:114},
  {name:"Parcel Yard", count:102},
  {name:"plusS", count:81},
  {name:"Promount", count:69},
  {name:"PERFKT-U", count:60},
  {name:"PURPLEMANGO THE FRUIT OF FASHION", count:56},
  {name:"Pierre Carlo", count:55},
  {name:"PRIMAL GRAY", count:54},
  {name:"PROTEENS", count:50},
  {name:"PERF", count:44},
  {name:"Pootlu", count:43},
  {name:"Peter England Elite", count:43},
  {name:"POSHAX", count:41},
  {name:"PS By Paul Smith", count:38},
  {name:"PYRO SPIRIT", count:36},
  {name:"PURE KNITS", count:27},
  {name:"PROWL by Tiger Shroff", count:25},
  {name:"PRORIDERS", count:25},
  {name:"PLATYPUSS", count:24},
  {name:"PETER ENGLAND UNIVERSITY", count:20},
  {name:"Peter England Better Jeans Company", count:20},
  {name:"PRINCINN MEYER", count:19},
  {name:"PAUSE SPORT", count:18},
  {name:"Pace International", count:18},
  {name:"PSG", count:17},
  {name:"Purple State", count:15},
  {name:"PRINTCULTR", count:15},
  {name:"PASSPORT JEANS", count:15},
  {name:"Peach", count:14},
  {name:"Peach & Lemonade", count:10},
  {name:"PUMA Hoops", count:9},
  {name:"Proline Active", count:9},
  {name:"PEPPYZONE", count:9},
  {name:"Paper Cut", count:8},
  {name:"PULAKIN", count:7},
  {name:"Praizy", count:6},
  {name:"Proline", count:5},
  {name:"PIVL", count:4},
  {name:"PRRODALITY", count:3},
  {name:"PREEN", count:3},
  {name:"Polo Tribe", count:2},
  {name:"POKER ACTIVE", count:2},
  {name:"Pepe", count:2},
  {name:"Pure Play", count:1},
  {name:"Prowl", count:1},
  {name:"PAREKH & SONS", count:1},

  {name:"QUCO", count:119},
  {name:"Q CUT", count:21},
  {name:"QENY", count:12},
  {name:"Qure Vintage", count:5},
  {name:"Quwa", count:1},

  {name:"Roadster", count:6205},
  {name:"R.Code by The Roadster Life Co.", count:1641},
  {name:"RARE RABBIT", count:1472},
  {name:"R&B", count:807},
  {name:"Reebok", count:762},
  {name:"Rigo", count:583},
  {name:"rock.it", count:404},
  {name:"Red Tape", count:342},
  {name:"Red Flame", count:317},
  {name:"Royal Enfield", count:256},
  {name:"Raymond", count:208},
  {name:"recast", count:197},
  {name:"RENUOVO", count:166},
  {name:"Rodzen", count:152},
  {name:"RAPL", count:152},
  {name:"REPRISE", count:143},
  {name:"Rodamo", count:119},
  {name:"RELANE", count:101},
  {name:"Richlook", count:100},
  {name:"REDESIGN", count:85},
  {name:"RHINO CULT", count:83},
  {name:"RISS", count:78},
  {name:"REYA", count:75},
  {name:"Ramraj", count:69},
  {name:"R.ARHAN PREMIUM", count:62},
  {name:"RAVINIK", count:52},
  {name:"ROAR FOR GOOD", count:48},
  {name:"ROYALTAIL", count:36},
  {name:"Reebok Classic", count:35},
  {name:"Roadking", count:34},
  {name:"Rivolta", count:34},
  {name:"Raxedo", count:33},
  {name:"Raimbera", count:21},
  {name:"Reccy", count:17},
  {name:"RUG WOODS", count:12},
  {name:"Reid & Taylor", count:12},
  {name:"RAHI TRENDZ", count:12},
  {name:"Rute", count:11},
  {name:"RIPOFF", count:11},
  {name:"ROAD RIDER", count:10},
  {name:"Red Chief", count:9},
  {name:"Reshavio", count:8},
  {name:"RAJUBHAI HARGOVINDAS", count:8},
  {name:"ROMEO ROSSI", count:6},
  {name:"RESA", count:6},
  {name:"RELIGHT WEARS", count:6},
  {name:"ROSANI", count:5},
  {name:"RAPTOR BROTHERS", count:5},
  {name:"Routeen", count:3},
  {name:"Regent Raiment", count:3},
  {name:"Ruggers", count:2},
  {name:"Rotaqo", count:1},
  {name:"Riot", count:1},
  {name:"Real Madrid", count:1},
  {name:"rabby", count:1},

  {name:"SZN", count:3331},
  {name:"StyleCast x Revolte", count:2597},
  {name:"SLOWLORIS", count:2020},
  {name:"StyleCast", count:1851},
  {name:"SPYKAR", count:1365},
  {name:"Snitch", count:1178},
  {name:"Status Quo", count:950},
  {name:"Sztori", count:736},
  {name:"SF JEANS by Pantaloons", count:643},
  {name:"SHOWOFF", count:508},
  {name:"Steenbok", count:443},
  {name:"Stitchmeashirt", count:377},
  {name:"SIMON CARTER LONDON", count:323},
  {name:"Stelino", count:239},
  {name:"STELLERS", count:232},
  {name:"SELECTED", count:232},
  {name:"SANDPIPER", count:204},
  {name:"SAIKSA FASHION", count:199},
  {name:"SWAGNOX", count:196},
  {name:"Santonio", count:194},
  {name:"Street 808 by Pantaloons", count:190},
  {name:"SMAN", count:185},
  {name:"SPORTO", count:172},
  {name:"Sparky", count:169},
  {name:"Stormborn", count:163},
  {name:"STELVIN", count:161},
  {name:"Skechers", count:161},
  {name:"SHOWOFFFF", count:160},
  {name:"STARFOX", count:158},
  {name:"SUN 'N' SUMMER", count:156},
  {name:"SMARTEES", count:144},
  {name:"SOLACEACTIVE", count:143},
  {name:"Shiv Naresh", count:143},
  {name:"SG", count:136},
  {name:"SPLOOSH", count:129},
  {name:"Sports52 wear", count:120},
  {name:"Supa", count:119},
  {name:"Streetsutra", count:114},
  {name:"SAGEWARE", count:94},
  {name:"SILISOUL", count:92},
  {name:"SANE ORIGINALS", count:92},
  {name:"SPORT SUN", count:89},
  {name:"Styli", count:84},
  {name:"STRCH", count:78},
  {name:"Slazenger", count:71},
  {name:"SPORTRIVER", count:70},
  {name:"Silver Moon Clothing", count:69},
  {name:"SOKO STREET", count:66},
  {name:"Sizeupp", count:65},
  {name:"Seekbuylove", count:64},
  {name:"SmileyWorld", count:62},
  {name:"Shrey", count:60},
  {name:"SKYKNIT", count:58},
  {name:"SIX5SIX", count:57},
  {name:"Star Wars by Wear Your Mind", count:56},
  {name:"Slowave", count:47},
  {name:"SQUIREHOOD", count:46},
  {name:"SleepZ by Raymond", count:46},
  {name:"SIAPA", count:37},
  {name:"Stitch Hub", count:34},
  {name:"Sweet Dreams", count:32},
  {name:"SONIBROS", count:32},
  {name:"Skidlers", count:31},
  {name:"SENO TEX", count:31},
  {name:"SUMISO", count:28},
  {name:"SUPERVEK", count:27},
  {name:"SUBTRACT", count:25},
  {name:"String Scape", count:24},
  {name:"SEMIR", count:24},
  {name:"Stylecast X Kotty", count:23},
  {name:"SHAUN", count:23},
  {name:"SOBERSAINT", count:20},
  {name:"SNUG24", count:19},
  {name:"Smugglerz", count:17},
  {name:"SKYBEN", count:16},
  {name:"SHOWKEY", count:16},
  {name:"SANHOK", count:14},
  {name:"STYLOGUE", count:13},
  {name:"Slub", count:13},
  {name:"Shop Football", count:12},
  {name:"STAR WARS", count:11},
  {name:"Sam and Jack", count:11},
  {name:"Splash", count:10},
  {name:"SOLSTICE", count:10},
  {name:"SINGLE", count:10},
  {name:"SANDCLOCK", count:10},
  {name:"SULLITT", count:9},
  {name:"STAG GLOBAL", count:8},
  {name:"Siddhant Agrawal", count:8},
  {name:"SHARKTRIBE", count:8},
  {name:"Steele", count:7},
  {name:"Sattired", count:7},
  {name:"SYMVI", count:6},
  {name:"Style Quotient", count:6},
  {name:"Sleek and Peek", count:6},
  {name:"Starsbuyer", count:5},
  {name:"SAMANT CHAUHAN", count:5},
  {name:"SAKHWALA", count:5},
  {name:"Studd Muffyn", count:4},
  {name:"Spolei", count:4},
  {name:"SMUGGLERZ INC.", count:4},
  {name:"SCROTT FITNESS", count:4},
  {name:"SAINTBLACK", count:4},
  {name:"SYMBLANCE", count:3},
  {name:"SPORTS VILLA", count:3},
  {name:"SHIRT THEORY", count:3},
  {name:"SAMRIZ", count:3},
  {name:"SXV STYLE", count:2},
  {name:"Sloggi", count:2},
  {name:"SOULIVELY", count:1},
  {name:"Sleepynuts", count:1},
  {name:"SKULT by Shahid Kapoor", count:1},
  {name:"SKATRD", count:1},
  {name:"shershaan", count:1},
  {name:"SENJARYA TIMES", count:1},
  {name:"Scooby Doo by Wear Your Mind", count:1},
  {name:"Sacriti", count:1},
  {name:"s.Oliver", count:1},

  {name:"Tommy Hilfiger", count:4434},
  {name:"The Souled Store", count:1302},
  {name:"Technosport", count:1193},
  {name:"THE BEAR HOUSE", count:1077},
  {name:"The Indian Garage Co", count:1027},
  {name:"Trendyol", count:892},
  {name:"THE BEETEL HOUSE", count:755},
  {name:"TOGS & TERRE", count:610},
  {name:"t-base", count:456},
  {name:"Thomas Scott", count:346},
  {name:"Turtle", count:337},
  {name:"THE HOLLANDER", count:313},
  {name:"Toodle Plus", count:306},
  {name:"TRIPR", count:278},
  {name:"TQH", count:273},
  {name:"THE MILLION CLUB", count:271},
  {name:"THE CHAMBAL", count:251},
  {name:"TheBTclub", count:243},
  {name:"True Religion", count:205},
  {name:"T.T.", count:190},
  {name:"Tantra", count:183},
  {name:"TIM PARIS", count:164},
  {name:"The Korhean Store", count:147},
  {name:"TQS", count:119},
  {name:"TIMBER HITCH", count:108},
  {name:"TEEFOX", count:103},
  {name:"The Dry State", count:101},
  {name:"The Mad Riyazi", count:99},
  {name:"TAJNAN", count:95},
  {name:"TRAVIS MATHEW", count:84},
  {name:"THE CASUALS", count:66},
  {name:"TICOSS", count:65},
  {name:"The Modern Soul", count:62},
  {name:"TURMS", count:57},
  {name:"TOXA", count:51},
  {name:"TMO", count:50},
  {name:"TVS", count:45},
  {name:"Ted Baker", count:44},
  {name:"Truerevo", count:40},
  {name:"THREADWOLF", count:39},
  {name:"TEEMOODS", count:36},
  {name:"Trenz", count:34},
  {name:"THREADCURRY", count:31},
  {name:"T-HUSTLER", count:31},
  {name:"THE CLOTHING FACTORY", count:30},
  {name:"THIRD ELEMENT", count:29},
  {name:"THINC", count:29},
  {name:"TURNFIT", count:28},
  {name:"TITTLI", count:28},
  {name:"TAZO", count:27},
  {name:"TIFTON", count:22},
  {name:"The North Face", count:20},
  {name:"Terra Luna", count:20},
  {name:"TOM BURG", count:19},
  {name:"The Tie Hub", count:19},
  {name:"TENHEM", count:18},
  {name:"Tees Da", count:18},
  {name:"TREERANGA", count:16},
  {name:"THREE DAYS", count:16},
  {name:"THIRD QUADRANT", count:16},
  {name:"Trends Tower", count:15},
  {name:"TRAQUILA", count:14},
  {name:"TRUE BASKET", count:13},
  {name:"Triple Dot", count:13},
  {name:"TOFFLE", count:12},
  {name:"THEYAYACAFE", count:11},
  {name:"THE SOUL PATROL", count:11},
  {name:"THALASI", count:11},
  {name:"TEGO", count:11},
  {name:"The Stanch", count:10},
  {name:"Tee Republic", count:10},
  {name:"Triumph", count:9},
  {name:"TANYAA", count:9},
  {name:"TANDUL", count:9},
  {name:"The Sea Horse", count:8},
  {name:"TERAXO", count:8},
  {name:"Tom & Jerry by Wear Your Mind", count:7},
  {name:"THE EG STORE", count:7},
  {name:"TrulyFeb", count:6},
  {name:"TroopLine", count:5},
  {name:"TOFFCRAFT", count:5},
  {name:"The Hustle Groove Co.", count:5},
  {name:"TESSIO", count:5},
  {name:"TESON", count:5},
  {name:"teeside", count:5},
  {name:"Tagfits London", count:5},
  {name:"TRENDY ERA", count:4},
  {name:"TRYWOLF", count:3},
  {name:"True Blue", count:3},
  {name:"TONES", count:3},
  {name:"Tom Tailor", count:3},
  {name:"Tinted", count:2},
  {name:"The Noise Culture", count:2},
  {name:"test", count:2},
  {name:"Teeshut", count:2},
  {name:"Trend Level", count:1},
  {name:"Top Gun", count:1},
  {name:"Tiktauli De Corps.", count:1},
  {name:"THREADS OF HARMAN", count:1},
  {name:"Threadbare", count:1},
  {name:"TBS- THE BARGAIN STREET", count:1},
  {name:"T-SHIRT TRUCK", count:1},
  
  {name:"U.S. Polo Assn.", count:3918},
  {name:"U.S. Polo Assn. Denim Co.", count:2237},
  {name:"UNDER ARMOUR", count:1363},
  {name:"United Colors of Benetton", count:1320},
  {name:"Underrated Club", count:563},
  {name:"Urban Ranger by pantaloons", count:307},
  {name:"URBANICE", count:204},
  {name:"Urbano Fashion", count:196},
  {name:"UNIBERRY", count:173},
  {name:"UNSULLY", count:149},
  {name:"Urbano Plus", count:129},
  {name:"UNRL", count:124},
  {name:"UNIQSOME", count:109},
  {name:"UNSIZED", count:88},
  {name:"Uniplanet store", count:82},
  {name:"UBX", count:76},
  {name:"Urban Dog", count:72},
  {name:"USPA Sport", count:65},
  {name:"UNSTD", count:55},
  {name:"UnderJeans by Spykar", count:53},
  {name:"URBAN FLAUNT", count:51},
  {name:"UpClothing", count:50},
  {name:"Unibro", count:43},
  {name:"Unicus Apparel", count:36},
  {name:"UrGear", count:28},
  {name:"UNSOMBER", count:27},
  {name:"Urban Monkey", count:26},
  {name:"UD FABRIC", count:22},
  {name:"USPA Active", count:20},
  {name:"URA STREET", count:19},
  {name:"Unfussy", count:17},
  {name:"URBAN KANYA", count:16},
  {name:"UMILDO", count:10},
  {name:"Untamed Clothing", count:9},
  {name:"Uneek", count:6},
  {name:"Uttam", count:5},
  {name:"UG SPORTS", count:5},
  {name:"Unseen Gods", count:4},
  {name:"uniformer", count:3},
  {name:"UZARUS", count:2},
  {name:"URBARO", count:2},
  {name:"Unisopent Designs", count:2},
  {name:"Urban Scissors", count:1},
  {name:"URBAN EAGLE by Pantaloons", count:1},
  {name:"UNTLD", count:1},
  {name:"UDI n ADI", count:1},
  {name:"UCLA", count:1},

  {name:"V-Mart", count:2114},
  {name:"VEIRDO", count:607},
  {name:"Van Heusen", count:581},
  {name:"Van Heusen Sport", count:423},
  {name:"Van Heusen Flex", count:372},
  {name:"Van Heusen Innerwear", count:356},
  {name:"VECTOR X", count:156},
  {name:"Voi Jeans", count:134},
  {name:"VeBNoR", count:134},
  {name:"VAN HEUSEN DENIM LABS", count:134},
  {name:"VENITIAN", count:129},
  {name:"VERO AMORE", count:50},
  {name:"VUDU", count:42},
  {name:"Vogue93", count:42},
  {name:"Vibe The Hype", count:33},
  {name:"Versace Jeans Couture", count:32},
  {name:"Vaishvik", count:30},
  {name:"VALKYRE", count:25},
  {name:"VS", count:17},
  {name:"Vivaan Fab", count:15},
  {name:"VIP", count:14},
  {name:"VILLAIN", count:14},
  {name:"VELLURE", count:14},
  {name:"VOLTEDGE", count:12},
  {name:"VOGAAN", count:10},
  {name:"VESTIDO MODAS", count:10},
  {name:"Valencia Fashion", count:9},
  {name:"VRIKSH", count:8},
  {name:"VASTRADO", count:6},
  {name:"VERO LIE", count:2},
  {name:"VICTORY", count:1},

  {name:"WOOSTRO", count:11412},
  {name:"WROGN", count:2315},
  {name:"Wrangler", count:585},
  {name:"Wear Your Mind", count:542},
  {name:"Wear Your Opinion", count:325},
  {name:"WILD ELEPHANT", count:236},
  {name:"WEARDUDS", count:177},
  {name:"WILD WEST", count:151},
  {name:"Wildcraft", count:147},
  {name:"Woodland", count:132},
  {name:"WEXFORD", count:86},
  {name:"WHITE HUSK", count:75},
  {name:"Woods", count:68},
  {name:"WATAY", count:52},
  {name:"Wod Armour", count:48},
  {name:"WILD COPS", count:48},
  {name:"WE PERFECT", count:45},
  {name:"Weezy", count:44},
  {name:"WANDERLOOMS", count:42},
  {name:"WESTTERA", count:28},
  {name:"WAIMEA", count:23},
  {name:"WOBE", count:22},
  {name:"WILD WEST Plus", count:15},
  {name:"WROGN ACTIVE", count:13},
  {name:"Wyld Sprog", count:12},
  {name:"Wildbrocket", count:9},
  {name:"WEVOK WEAR", count:9},
  {name:"Wellbi", count:9},
  {name:"Wills Lifestyle", count:7},
  {name:"WEET", count:7},
  {name:"WALAWALI", count:3},
  {name:"WRIGHTRACK", count:1},
  {name:"Wrath", count:1},

  {name:"XYXX", count:218},
  {name:"Xtep", count:111},
  {name:"Xmex", count:99},
  {name:"XFOX", count:64},
  {name:"XYRIS", count:44},
  {name:"Xenpachi", count:25},
  {name:"Xalt Life", count:23},
  {name:"Xtrim", count:12},
  {name:"XCETRA", count:7},
  {name:"Xohy", count:2},

  {name:"YAK YAK", count:220},
  {name:"Yoorix", count:149},
  {name:"YHA", count:39},
  {name:"Y.O.U", count:30},
  {name:"YU by Pantaloons", count:6},
  {name:"Yazole", count:5},
  {name:"YWC", count:1},
  {name:"Yuuki", count:1},

  {name:"ZU", count:260},
  {name:"ZEFFIT", count:218},
  {name:"Zigo", count:159},
  {name:"Z Zagros", count:150},
  {name:"ZEDD", count:83},
  {name:"ZEN1 FASHION", count:79},
  {name:"Zenroz", count:45},
  {name:"zebu", count:22},
  {name:"Zeal", count:19},
  {name:"Zarlin", count:19},
  {name:"ZORI WORLD", count:10},
  {name:"ZYNG", count:8},
  {name:"ZERO TOLERANCE", count:7},
  {name:"ZALORA BASICS", count:6},
  {name:"Zage", count:3},
  {name:"ZEROZABAR", count:1},
  {name:"ZAMBYFASHION", count:1},
  {name:"ZALORA ACTIVE", count:1}
  ];

  const alphabets = [
    "#",
    ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)),
  ];


  const [showMore, setShowMore] = useState(false); // brand panel
  const [showSearch, setShowSearch] = useState(false); // small search bar toggle
  const [searchTerm, setSearchTerm] = useState("");
  const [hoveredLetter, setHoveredLetter] = useState(null);

  const filteredBrands = brands.filter((b) =>
    b.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Group brands by first letter
  const groupedBrands = {};
  filteredBrands.forEach((brand) => {
    const firstChar = /^[0-9]/.test(brand.name[0])
      ? "#"
      : brand.name[0].toUpperCase();
    if (!groupedBrands[firstChar]) groupedBrands[firstChar] = [];
    groupedBrands[firstChar].push(brand);
  });


    return (
    <div className="mb-3">
      {/* Header with Search */}
      <div className="d-flex justify-content-between align-items-center mb-2">
        {!showSearch && (
          <h4 className="fw-bold fs-6 text-dark m-0">BRAND</h4>
        )}

        {!showSearch ? (
          <div
            style={{
              width: "28px",
              height: "28px",
              borderRadius: "50%",
              backgroundColor: "#f0f0f0",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              cursor: "pointer",
              transition: "all 0.3s ease",
            }}
            onClick={() => setShowSearch(true)}
          >
            <Search size={16} color="gray" />
          </div>
        ) : (
          <div
            className="d-flex align-items-center"
            style={{
              background: "#f5f5f6",
              borderRadius: "20px",
              padding: "4px 8px",
              width: "100%",
              maxWidth: "220px",
              transition: "all 0.3s ease",
              boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
            }}
          >
            <input
              type="text"
              placeholder="Search Brand"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{
                border: "none",
                outline: "none",
                background: "transparent",
                fontSize: "13px",
                flex: 1,
              }}
            />
            <X
              size={18}
              style={{ cursor: "pointer", marginLeft: "6px" }}
              onClick={() => {
                setSearchTerm("");
                setShowSearch(false);
              }}
            />
          </div>
        )}
      </div>

      {/* Top brands */}
      <div className="d-flex flex-column">
        {(searchTerm ? filteredBrands.slice(0, 8) : brands.slice(0, 8)).map(
          (item) => (
            <div key={item.name} className="d-flex align-items-center mb-2">
              <input
                type="checkbox"
                className="form-check-input me-2"
                id={`brand-${item.name}`}
              />
              <label htmlFor={`brand-${item.name}`}>
                {item.name} ({item.count})
              </label>
            </div>
          )
        )}

        {/* No Brands Found */}
        {searchTerm && filteredBrands.length === 0 && (
          <span className="text-muted small">No brands found</span>
        )}

        {/* +More */}
        {!searchTerm && (
          <span
            className="mt-1"
            style={{
              color: "rgb(252, 86, 113)",
              cursor: "pointer",
              fontWeight: "400",
            }}
            onClick={() => setShowMore(true)}
          >
            +1375 more
          </span>
        )}
      </div>

      {/* Side Panel */}
      {showMore && (
        <div
          className="position-fixed top-0 start-0 bg-white shadow-lg"
          style={{
            zIndex: 1050,
            width: "80%",
            height: "90%",
            overflow: "hidden",
            borderRadius: "8px",
            margin: "2% 10%",
          }}
        >
          {/* Header with Search + Close */}
          <div className="p-3 border-bottom d-flex justify-content-between align-items-center">
            <input
              type="text"
              className="form-control"
              placeholder="Search Brand"
              style={{ borderColor: "blue", maxWidth: "250px" }}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <X
              size={24}
              className="cursor-pointer"
              onClick={() => setShowMore(false)}
            />
          </div>

          {/* Alphabet bar */}
          <div className="px-3 py-2 border-bottom">
            <div className="d-flex flex-wrap">
              {alphabets.map((letter) => (
                <span
                  key={letter}
                  className="me-2 mb-1"
                  style={{
                    cursor: "pointer",
                    fontWeight: "500",
                    opacity:
                      hoveredLetter && hoveredLetter !== letter ? 0.4 : 1,
                  }}
                  onMouseEnter={() => setHoveredLetter(letter)}
                  onMouseLeave={() => setHoveredLetter(null)}
                >
                  {letter}
                </span>
              ))}
            </div>
          </div>

          {/* Brand Grid */}
          <div
            className="p-3"
            style={{
              maxHeight: "75%",
              overflowY: "auto",
              columnCount: 4,
              columnGap: "2rem",
            }}
          >
            {alphabets.map((letter) => {
              const brandsForLetter = groupedBrands[letter] || [];
              if (brandsForLetter.length === 0) return null;

              return (
                <div
                  key={letter}
                  style={{ breakInside: "avoid" }}
                  className="mb-3"
                >
                  <strong className="d-block mb-2">{letter}</strong>
                  {brandsForLetter.map((item) => {
                    const show = !hoveredLetter || hoveredLetter === letter;
                    return (
                      <div
                        key={item.name}
                        className="d-flex align-items-center mb-1"
                        style={{ opacity: show ? 1 : 0.3 }}
                      >
                        <input
                          type="checkbox"
                          className="form-check-input me-2"
                          id={`brand-panel-${item.name}`}
                        />
                        <label htmlFor={`brand-panel-${item.name}`}>
                          {item.name} ({item.count})
                        </label>
                      </div>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

export default FilterBrand;